In [1]:
!pip install pandas

Requirement already satisfied: pandas in /srv/conda/envs/notebook/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in /srv/conda/envs/notebook/lib/python3.11/site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /srv/conda/envs/notebook/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /srv/conda/envs/notebook/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /srv/conda/envs/notebook/lib/python3.11/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [13]:
import pandas as pd
import zipfile
import os
from pathlib import Path

In [15]:
##change working directory from notebooks to home
os.chdir("..")

In [25]:
##create dataframes for core OMOP tables

person = pd.read_csv("OMOP/person.csv")

condition_occurrence =pd.read_csv("OMOP/condition_occurrence.csv")

visit_occurrence = pd.read_csv("OMOP/visit_occurrence.csv")

drug_exposure = pd.read_csv("OMOP/drug_exposure.csv")

observations = pd.read_csv("OMOP/observation.csv")

procedure_occurrence = pd.read_csv("OMOP/procedure_occurrence.csv")

measurement = pd.read_csv("OMOP/measurement.csv", low_memory=False)

concept = pd.read_csv("OMOP/concepts.csv")

In [31]:
visit_occurrence.head()

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_datetime,visit_end_date,visit_end_datetime,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id,admitting_source_concept_id,admitting_source_value,discharge_to_concept_id,discharge_to_source_value,preceding_visit_occurrence_id
0,-4406053801395356975,4783904755296699562,38004207,2112-11-06,2112-11-06 11:05:00,2112-11-06,2112-11-06 11:05:00,32817,NaN,NaN,10035631|2112-11-06,2000001801,NaN,NaN,NaN,NaN,-3.100296e+18
1,2636026522589494723,-6225647829918357531,38004207,2153-10-17,2153-10-17 14:23:00,2153-10-17,2153-10-17 14:23:00,32817,NaN,NaN,10019003|2153-10-17,2000001801,NaN,NaN,NaN,NaN,-2.238366e+18
2,-8900473297538187901,7918537411740862407,38004207,2130-10-10,2130-10-10 16:20:00,2130-10-10,2130-10-10 16:20:00,32817,NaN,NaN,10020306|2130-10-10,2000001801,NaN,NaN,NaN,NaN,-8.600570e+18
3,-8091470952174089624,-6225647829918357531,38004207,2155-04-20,2155-04-20 09:00:00,2155-04-20,2155-04-20 09:00:00,32817,NaN,NaN,10019003|2155-04-20,2000001801,NaN,NaN,NaN,NaN,4.782862e+18
4,8144493519470334167,7155255168997124770,38004207,2147-07-08,2147-07-08 08:20:00,2147-07-08,2147-07-08 08:20:00,32817,NaN,NaN,10014354|2147-07-08,2000001801,NaN,NaN,NaN,NaN,-3.275690e+18

In [32]:
dataframe_vars = [var_name for var_name, var_val in globals().items() if isinstance(var_val, pd.DataFrame)]

print("DataFrames currently in memory:", dataframe_vars)

DataFrames currently in memory: ['_', '__', '___', 'person', 'condition_occurrence', 'visit_occurrence', 'drug_exposure', 'observations', 'proceure_occurrence', 'concept', 'measurement', '_26', '_28', '_29', '_31']

In [34]:
_.head()

,measurement_id,person_id,measurement_concept_id,measurement_date,measurement_datetime,measurement_time,measurement_type_concept_id,operator_concept_id,value_as_number,value_as_concept_id,unit_concept_id,range_low,range_high,provider_id,visit_occurrence_id,visit_detail_id,measurement_source_value,measurement_source_concept_id,unit_source_value,value_source_value
0,7620661609057829801,-7437341330444582833,3007913,2113-09-14,2113-09-14 10:41:00,NaN,32856,NaN,586.0,NaN,8876.0,NaN,NaN,NaN,3697313480337443666,NaN,50801,2.000001e+09,mm Hg,586
1,-6166868866082303206,-2312013739856114142,3012501,2116-07-05,2116-07-05 05:51:00,NaN,32856,NaN,-4.0,NaN,9557.0,NaN,NaN,NaN,-5005846256467230136,NaN,50802,2.000001e+09,mEq/L,-4
2,-5240588523649662838,-4234372750442829205,3012501,2154-01-02,2154-01-02 20:18:00,NaN,32856,NaN,-2.0,NaN,9557.0,NaN,NaN,NaN,-5317261811030552609,NaN,50802,2.000001e+09,mEq/L,-2
3,6455538495061268502,8805478484003283429,3012501,2114-06-20,2114-06-20 09:59:00,NaN,32856,NaN,3.0,NaN,9557.0,NaN,NaN,NaN,4821424463988433938,NaN,50802,2.000001e+09,mEq/L,3
4,8972684215776493449,6339505631013617478,3012501,2111-11-15,2111-11-15 03:09:00,NaN,32856,NaN,-2.0,NaN,9557.0,NaN,NaN,NaN,-6354047184485090226,NaN,50802,2.000001e+09,mEq/L,-2